In [2]:
import torch

1. 행렬 직접선언

In [9]:
x = torch.empty(5,3)
x

tensor([[0.7271, 0.0431, 0.6570],
        [0.2068, 0.4412, 0.7660],
        [0.4591, 0.2942, 0.4657],
        [0.1278, 0.4640, 0.9126],
        [0.6902, 0.6918, 0.8119]])

2. 랜덤행렬
    - 빈 행렬과 뒤에서 학습할 0 행렬은 다르다.

In [5]:
x = torch.rand(5,3)
x

tensor([[0.7271, 0.0431, 0.6570],
        [0.2068, 0.4412, 0.7660],
        [0.4591, 0.2942, 0.4657],
        [0.1278, 0.4640, 0.9126],
        [0.6902, 0.6918, 0.8119]])

4. identity

In [13]:
x = torch.eye(5,3)
print(x)
print(type(x))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>


Arrange

In [15]:
x = torch.arange(2,4,0.1)
print(f'x size:{x.size()}')
x

x size:torch.Size([20])


tensor([2.0000, 2.1000, 2.2000, 2.3000, 2.4000, 2.5000, 2.6000, 2.7000, 2.8000,
        2.9000, 3.0000, 3.1000, 3.2000, 3.3000, 3.4000, 3.5000, 3.6000, 3.7000,
        3.8000, 3.9000])

linspace

In [18]:
x = torch.linspace(start=2, end=8 ,steps=7)
print(x)

tensor([2., 3., 4., 5., 6., 7., 8.])


다른 Tensor로부터 생성하기

In [16]:
x_data = torch.linspace(start=0 , end=10, steps=20, dtype=torch.float16)

In [20]:
n = 10
k = 20
x = torch.rand(n,k)
y = torch.rand(n,k)

output = torch.cat()


tensor([[6.4622e-01, 9.8426e-01, 7.4712e-01, 4.3358e-01, 2.1016e-01, 2.8221e-01,
         8.9779e-01, 9.7154e-01, 2.4629e-02, 4.9555e-01, 6.7632e-01, 4.1871e-01,
         5.7193e-01, 5.5663e-01, 9.1938e-01, 9.3126e-01, 8.8273e-01, 4.6956e-01,
         8.0259e-02, 1.5237e-01],
        [2.4284e-02, 5.8657e-01, 5.6703e-01, 9.8844e-01, 2.0171e-01, 2.6377e-01,
         6.2794e-01, 1.8174e-01, 1.6072e-01, 6.4003e-01, 3.0940e-01, 5.4215e-01,
         4.4336e-01, 6.6011e-01, 9.0860e-01, 8.2235e-01, 2.6799e-01, 7.9560e-01,
         3.0022e-01, 1.2392e-01],
        [6.8386e-01, 7.3439e-01, 3.5512e-01, 4.6616e-02, 5.9110e-01, 5.9764e-01,
         4.8739e-01, 5.1458e-01, 5.7630e-01, 5.3315e-01, 9.5037e-01, 1.7839e-01,
         1.4380e-01, 7.4067e-01, 2.9683e-01, 9.1577e-01, 6.7004e-01, 3.0436e-01,
         2.8628e-01, 9.5595e-01],
        [8.4950e-01, 5.7686e-01, 2.9487e-01, 8.5323e-01, 6.5622e-03, 1.0348e-01,
         4.1122e-01, 5.8280e-01, 1.2281e-01, 9.7688e-01, 7.4605e-01, 5.5726e-01,
       

In [ ]:
batch_size = 5

