In [1]:
import torch

1. 행렬 직접선언

In [2]:
x = torch.empty(5,3)
x

tensor([[ 3.4825e+07,  4.5779e-41,  3.9660e+16],
        [-5.1640e-30,  5.3066e+07,  4.5779e-41],
        [ 3.4874e+07,  4.5779e-41, -2.8295e+08],
        [ 8.8718e+21,  5.3120e+07,  4.5779e-41],
        [ 3.4798e+07,  4.5779e-41, -1.6769e+32]])

2. 랜덤행렬
    - 빈 행렬과 뒤에서 학습할 0 행렬은 다르다.

In [3]:
x = torch.rand(5,3)
x

tensor([[0.2562, 0.0473, 0.8046],
        [0.7459, 0.3771, 0.4821],
        [0.1023, 0.5396, 0.5284],
        [0.5739, 0.7306, 0.8975],
        [0.8884, 0.2573, 0.7856]])

4. identity

In [4]:
x = torch.eye(5,3)
print(x)
print(type(x))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>


Arrange

In [5]:
x = torch.arange(2,4,0.1)
print(f'x size:{x.size()}')
x

x size:torch.Size([20])


tensor([2.0000, 2.1000, 2.2000, 2.3000, 2.4000, 2.5000, 2.6000, 2.7000, 2.8000,
        2.9000, 3.0000, 3.1000, 3.2000, 3.3000, 3.4000, 3.5000, 3.6000, 3.7000,
        3.8000, 3.9000])

linspace

In [6]:
x = torch.linspace(start=2, end=8 ,steps=7)
print(x)

tensor([2., 3., 4., 5., 6., 7., 8.])


다른 Tensor로부터 생성하기

In [7]:
x_data = torch.linspace(start=0 , end=10, steps=20, dtype=torch.float16)

In [8]:
n = 10
k = 20
x = torch.rand(n,k)
y = torch.rand(n,k)

output = torch.cat()


TypeError: cat() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of Tensors tensors, int dim, *, Tensor out)
 * (tuple of Tensors tensors, name dim, *, Tensor out)


In [ ]:
ko_vocab = create_or_load_token
